/* Imported exercise library: (name, category, equipment) triples carried over
 * from the earlier Personal-Trainer project. Mapped into this platform's
 * taxonomy by seeds/platform/mapping.ts - see that file for how. */

export const IMPORTED_EXERCISES: [name: string, category: string, equipment: string][] = [
  ["Barbell Bench Press","Chest","Barbell"],
  ["Incline Barbell Bench Press","Chest","Barbell"],
  ["Decline Barbell Bench Press","Chest","Barbell"],
  ["Dumbbell Bench Press","Chest","Dumbbell"],
  ["Incline Dumbbell Bench Press","Chest","Dumbbell"],
  ["Decline Dumbbell Bench Press","Chest","Dumbbell"],
  ["Dumbbell Flyes","Chest","Dumbbell"],
  ["Incline Dumbbell Flyes","Chest","Dumbbell"],
  ["Cable Crossover","Chest","Cable"],
  ["Low Cable Crossover","Chest","Cable"],
  ["Pec Deck Machine","Chest","Machine"],
  ["Machine Chest Press","Chest","Machine"],
  ["Push-Up","Chest","Bodyweight"],
  ["Decline Push-Up","Chest","Bodyweight"],
  ["Diamond Push-Up","Chest","Bodyweight"],
  ["Chest Dip","Chest","Bodyweight"],
  ["Landmine Press","Chest","Barbell"],
  ["Svend Press","Chest","Plate"],
  ["Barbell Deadlift","Back","Barbell"],
  ["Conventional Deadlift","Back","Barbell"],
  ["Sumo Deadlift","Back","Barbell"],
  ["Romanian Deadlift","Back","Barbell"],
  ["Barbell Row","Back","Barbell"],
  ["Pendlay Row","Back","Barbell"],
  ["T-Bar Row","Back","Barbell"],
  ["Dumbbell Row","Back","Dumbbell"],
  ["Kroc Row","Back","Dumbbell"],
  ["Seated Cable Row","Back","Cable"],
  ["Face Pull","Back","Cable"],
  ["Lat Pulldown","Back","Cable"],
  ["Wide-Grip Lat Pulldown","Back","Cable"],
  ["Close-Grip Lat Pulldown","Back","Cable"],
  ["Straight-Arm Pulldown","Back","Cable"],
  ["Pull-Up","Back","Bodyweight"],
  ["Chin-Up","Back","Bodyweight"],
  ["Neutral-Grip Pull-Up","Back","Bodyweight"],
  ["Inverted Row","Back","Bodyweight"],
  ["Machine Row","Back","Machine"],
  ["Chest-Supported Row","Back","Dumbbell"],
  ["Rack Pull","Back","Barbell"],
  ["Good Morning","Back","Barbell"],
  ["Hyperextension","Back","Bodyweight"],
  ["Overhead Press","Shoulders","Barbell"],
  ["Seated Barbell Press","Shoulders","Barbell"],
  ["Push Press","Shoulders","Barbell"],
  ["Dumbbell Shoulder Press","Shoulders","Dumbbell"],
  ["Arnold Press","Shoulders","Dumbbell"],
  ["Lateral Raise","Shoulders","Dumbbell"],
  ["Cable Lateral Raise","Shoulders","Cable"],
  ["Front Raise","Shoulders","Dumbbell"],
  ["Rear Delt Fly","Shoulders","Dumbbell"],
  ["Reverse Pec Deck","Shoulders","Machine"],
  ["Upright Row","Shoulders","Barbell"],
  ["Cable Upright Row","Shoulders","Cable"],
  ["Machine Shoulder Press","Shoulders","Machine"],
  ["Plate Front Raise","Shoulders","Plate"],
  ["Bradford Press","Shoulders","Barbell"],
  ["Lu Raise","Shoulders","Dumbbell"],
  ["Barbell Back Squat","Quadriceps","Barbell"],
  ["Barbell Front Squat","Quadriceps","Barbell"],
  ["Goblet Squat","Quadriceps","Dumbbell"],
  ["Hack Squat","Quadriceps","Machine"],
  ["Leg Press","Quadriceps","Machine"],
  ["Leg Extension","Quadriceps","Machine"],
  ["Bulgarian Split Squat","Quadriceps","Dumbbell"],
  ["Walking Lunge","Quadriceps","Dumbbell"],
  ["Reverse Lunge","Quadriceps","Dumbbell"],
  ["Step-Up","Quadriceps","Dumbbell"],
  ["Sissy Squat","Quadriceps","Bodyweight"],
  ["Wall Sit","Quadriceps","Bodyweight"],
  ["Box Squat","Quadriceps","Barbell"],
  ["Zercher Squat","Quadriceps","Barbell"],
  ["Pistol Squat","Quadriceps","Bodyweight"],
  ["Smith Machine Squat","Quadriceps","Machine"],
  ["Lying Leg Curl","Hamstrings","Machine"],
  ["Seated Leg Curl","Hamstrings","Machine"],
  ["Nordic Hamstring Curl","Hamstrings","Bodyweight"],
  ["Stiff-Leg Deadlift","Hamstrings","Barbell"],
  ["Dumbbell Romanian Deadlift","Hamstrings","Dumbbell"],
  ["Single-Leg Romanian Deadlift","Hamstrings","Dumbbell"],
  ["Glute-Ham Raise","Hamstrings","Bodyweight"],
  ["Cable Pull-Through","Hamstrings","Cable"],
  ["Kettlebell Swing","Hamstrings","Kettlebell"],
  ["Barbell Hip Thrust","Glutes","Barbell"],
  ["Dumbbell Hip Thrust","Glutes","Dumbbell"],
  ["Glute Bridge","Glutes","Bodyweight"],
  ["Single-Leg Glute Bridge","Glutes","Bodyweight"],
  ["Cable Kickback","Glutes","Cable"],
  ["Sumo Squat","Glutes","Dumbbell"],
  ["Frog Pump","Glutes","Bodyweight"],
  ["Banded Clamshell","Glutes","Band"],
  ["Lateral Band Walk","Glutes","Band"],
  ["Donkey Kick","Glutes","Bodyweight"],
  ["Standing Calf Raise","Calves","Machine"],
  ["Seated Calf Raise","Calves","Machine"],
  ["Donkey Calf Raise","Calves","Machine"],
  ["Single-Leg Calf Raise","Calves","Bodyweight"],
  ["Smith Machine Calf Raise","Calves","Machine"],
  ["Barbell Curl","Biceps","Barbell"],
  ["EZ-Bar Curl","Biceps","Barbell"],
  ["Dumbbell Curl","Biceps","Dumbbell"],
  ["Hammer Curl","Biceps","Dumbbell"],
  ["Incline Dumbbell Curl","Biceps","Dumbbell"],
  ["Concentration Curl","Biceps","Dumbbell"],
  ["Preacher Curl","Biceps","Barbell"],
  ["Cable Curl","Biceps","Cable"],
  ["Spider Curl","Biceps","Dumbbell"],
  ["Reverse Curl","Biceps","Barbell"],
  ["Zottman Curl","Biceps","Dumbbell"],
  ["Drag Curl","Biceps","Barbell"],
  ["Machine Curl","Biceps","Machine"],
  ["Cross-Body Hammer Curl","Biceps","Dumbbell"],
  ["21s (Bicep 21s)","Biceps","Barbell"],
  ["Close-Grip Bench Press","Triceps","Barbell"],
  ["Tricep Dip","Triceps","Bodyweight"],
  ["Skull Crusher","Triceps","Barbell"],
  ["EZ-Bar Skull Crusher","Triceps","Barbell"],
  ["Overhead Tricep Extension","Triceps","Dumbbell"],
  ["Cable Tricep Pushdown","Triceps","Cable"],
  ["Rope Pushdown","Triceps","Cable"],
  ["Kickback","Triceps","Dumbbell"],
  ["Tricep Diamond Push-Up","Triceps","Bodyweight"],
  ["JM Press","Triceps","Barbell"],
  ["Tate Press","Triceps","Dumbbell"],
  ["French Press","Triceps","Barbell"],
  ["Single-Arm Cable Pushdown","Triceps","Cable"],
  ["Wrist Curl","Forearms","Barbell"],
  ["Reverse Wrist Curl","Forearms","Barbell"],
  ["Farmer's Walk","Forearms","Dumbbell"],
  ["Plate Pinch Hold","Forearms","Plate"],
  ["Dead Hang","Forearms","Bodyweight"],
  ["Towel Pull-Up","Forearms","Bodyweight"],
  ["Fat Grip Hold","Forearms","Barbell"],
  ["Plank","Core","Bodyweight"],
  ["Side Plank","Core","Bodyweight"],
  ["Ab Wheel Rollout","Core","Ab Wheel"],
  ["Hanging Leg Raise","Core","Bodyweight"],
  ["Hanging Knee Raise","Core","Bodyweight"],
  ["Cable Crunch","Core","Cable"],
  ["Russian Twist","Core","Bodyweight"],
  ["Bicycle Crunch","Core","Bodyweight"],
  ["V-Up","Core","Bodyweight"],
  ["Dragon Flag","Core","Bodyweight"],
  ["Pallof Press","Core","Cable"],
  ["Woodchop","Core","Cable"],
  ["Dead Bug","Core","Bodyweight"],
  ["Bird Dog","Core","Bodyweight"],
  ["Sit-Up","Core","Bodyweight"],
  ["Decline Sit-Up","Core","Bodyweight"],
  ["Leg Raise","Core","Bodyweight"],
  ["Mountain Climber","Core","Bodyweight"],
  ["Flutter Kick","Core","Bodyweight"],
  ["Hollow Body Hold","Core","Bodyweight"],
  ["L-Sit","Core","Bodyweight"],
  ["Suitcase Carry","Core","Dumbbell"],
  ["Turkish Get-Up","Core","Kettlebell"],
  ["Clean and Jerk","Olympic","Barbell"],
  ["Power Clean","Olympic","Barbell"],
  ["Hang Clean","Olympic","Barbell"],
  ["Snatch","Olympic","Barbell"],
  ["Power Snatch","Olympic","Barbell"],
  ["Hang Snatch","Olympic","Barbell"],
  ["Clean Pull","Olympic","Barbell"],
  ["Snatch Pull","Olympic","Barbell"],
  ["Thruster","Olympic","Barbell"],
  ["Treadmill Run","Cardio","Machine"],
  ["Incline Treadmill Walk","Cardio","Machine"],
  ["Stationary Bike","Cardio","Machine"],
  ["Rowing Machine","Cardio","Machine"],
  ["Elliptical","Cardio","Machine"],
  ["Stair Climber","Cardio","Machine"],
  ["Jump Rope","Cardio","Equipment"],
  ["Battle Ropes","Cardio","Equipment"],
  ["Box Jump","Cardio","Bodyweight"],
  ["Burpee","Cardio","Bodyweight"],
  ["Jumping Jack","Cardio","Bodyweight"],
  ["Sprint","Cardio","Bodyweight"],
  ["Sled Push","Cardio","Equipment"],
  ["Sled Pull","Cardio","Equipment"],
  ["Assault Bike","Cardio","Machine"],
  ["Ski Erg","Cardio","Machine"],
  ["Foam Roll - IT Band","Mobility","Foam Roller"],
  ["Foam Roll - Quads","Mobility","Foam Roller"],
  ["Foam Roll - Back","Mobility","Foam Roller"],
  ["Foam Roll - Calves","Mobility","Foam Roller"],
  ["Hip Flexor Stretch","Mobility","Bodyweight"],
  ["Pigeon Stretch","Mobility","Bodyweight"],
  ["Cat-Cow Stretch","Mobility","Bodyweight"],
  ["World's Greatest Stretch","Mobility","Bodyweight"],
  ["90/90 Hip Stretch","Mobility","Bodyweight"],
  ["Thoracic Spine Rotation","Mobility","Bodyweight"],
  ["Banded Shoulder Distraction","Mobility","Band"],
  ["Lacrosse Ball Pec Release","Mobility","Lacrosse Ball"],
  ["Wall Slide","Mobility","Bodyweight"],
  ["Couch Stretch","Mobility","Bodyweight"],
  ["Standing Hamstring Stretch","Mobility","Bodyweight"],
  ["Supine Spinal Twist","Mobility","Bodyweight"],
  ["Child's Pose","Mobility","Bodyweight"],
  ["Downward Dog","Mobility","Bodyweight"],
  ["Depth Jump","Plyometrics","Bodyweight"],
  ["Broad Jump","Plyometrics","Bodyweight"],
  ["Lateral Bound","Plyometrics","Bodyweight"],
  ["Tuck Jump","Plyometrics","Bodyweight"],
  ["Plyo Push-Up","Plyometrics","Bodyweight"],
  ["Single-Leg Hop","Plyometrics","Bodyweight"],
  ["Skater Jump","Plyometrics","Bodyweight"],
  ["Squat Jump","Plyometrics","Bodyweight"],
  ["Sandbag Carry","Functional","Sandbag"],
  ["Atlas Stone Lift","Functional","Stone"],
  ["Tire Flip","Functional","Tire"],
  ["Medicine Ball Slam","Functional","Medicine Ball"],
  ["Wall Ball","Functional","Medicine Ball"],
  ["Rope Climb","Functional","Rope"],
  ["Bear Crawl","Functional","Bodyweight"],
  ["Crab Walk","Functional","Bodyweight"],
  ["Inchworm","Functional","Bodyweight"],
];
